In [1]:
# Import dependencies
import pandas as pd

In [2]:
# List of 2018 file names to be combined 
files2018 = ['citibike_data/JC-201801-citibike-tripdata.csv', 'citibike_data/JC-201802-citibike-tripdata.csv', 'citibike_data/JC-201803-citibike-tripdata.csv', 'citibike_data/JC-201804-citibike-tripdata.csv', 'citibike_data/JC-201805-citibike-tripdata.csv', 'citibike_data/JC-201806-citibike-tripdata.csv', 'citibike_data/JC-201807-citibike-tripdata.csv', 'citibike_data/JC-201808-citibike-tripdata.csv', 'citibike_data/JC-201809-citibike-tripdata.csv', 'citibike_data/JC-201810-citibike-tripdata.csv', 'citibike_data/JC-201811-citibike-tripdata.csv', 'citibike_data/JC-201812-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2018_list = []

# Loop through each file in the list
for file in files2018:
    # Read the file into a dataframe
    df2018 = pd.read_csv(file)

    # Append the dataframe to the list
    df2018_list.append(df2018)

# Concatenate all dataframes in the list into one dataframe
df2018 = pd.concat(df2018_list)

# Drop rows with null values
df2018 = df2018.dropna()

# Show dataframe
df2018.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1

In [3]:
# List of 2019 file names to be combined 
files2019 = ['citibike_data/JC-201901-citibike-tripdata.csv', 'citibike_data/JC-201902-citibike-tripdata.csv', 'citibike_data/JC-201903-citibike-tripdata.csv', 'citibike_data/JC-201904-citibike-tripdata.csv', 'citibike_data/JC-201905-citibike-tripdata.csv', 'citibike_data/JC-201906-citibike-tripdata.csv', 'citibike_data/JC-201907-citibike-tripdata.csv', 'citibike_data/JC-201908-citibike-tripdata.csv', 'citibike_data/JC-201909-citibike-tripdata.csv', 'citibike_data/JC-201910-citibike-tripdata.csv', 'citibike_data/JC-201911-citibike-tripdata.csv', 'citibike_data/JC-201912-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2019_list = []

# Loop through each file in the list
for file in files2019:
    # Read the file into a dataframe
    df2019 = pd.read_csv(file)

    # Append the dataframe to the list
    df2019_list.append(df2019)

# Concatenate all dataframes in the list into one dataframe
df2019 = pd.concat(df2019_list)

# Drop rows with null values
df2019 = df2019.dropna()

# Show dataframe
df2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,283,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1
19724,267,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1
19725,379,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717732,-74.043845,26276,Subscriber,1984,1
19726,188,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1
19727,326,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1

In [4]:
# List of 2020 file names to be combined 
files2020 = ['citibike_data/JC-202001-citibike-tripdata.csv', 'citibike_data/JC-202002-citibike-tripdata.csv', 'citibike_data/JC-202003-citibike-tripdata.csv', 'citibike_data/JC-202004-citibike-tripdata.csv', 'citibike_data/JC-202005-citibike-tripdata.csv', 'citibike_data/JC-202006-citibike-tripdata.csv', 'citibike_data/JC-202007-citibike-tripdata.csv', 'citibike_data/JC-202008-citibike-tripdata.csv', 'citibike_data/JC-202009-citibike-tripdata.csv', 'citibike_data/JC-202010-citibike-tripdata.csv', 'citibike_data/JC-202011-citibike-tripdata.csv', 'citibike_data/JC-202012-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2020_list = []

# Loop through each file in the list
for file in files2020:
    # Read the file into a dataframe
    df2020 = pd.read_csv(file)

    # Append the dataframe to the list
    df2020_list.append(df2020)

# Concatenate all dataframes in the list into one dataframe
df2020 = pd.concat(df2020_list)

# Drop rows with null values
df2020 = df2020.dropna()

# Show dataframe
df2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [5]:
# Concatenate all dataframes for all the years into one file dataframe
combined_df = pd.concat([df2018, df2019, df2020], axis=0)

# Display the results
combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [ ]:
# Save the final dataframe to a CSV file
combined_df.to_csv('citibike_data/citibike.csv', index=False)